name: Build ESPHome Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual runs

permissions:
  contents: write
  
jobs:
  build-firmware:
    runs-on: ubuntu-latest
    name: build
    strategy:
      matrix:
        files:
          - "circuitsetup-gdo-default.yaml"
          - "6chan_energy_meter_main_board.yaml"
          - "6chan_energy_meter_main_ethernet.yaml"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download ESPHome Config Files
        run: |
          curl -L -o circuitsetup-gdo-default.yaml https://raw.githubusercontent.com/CircuitSetup/circuitsetup-esphome/master/circuitsetup-gdo-default.yaml
          curl -L -o 6chan_energy_meter_main_board.yaml https://raw.githubusercontent.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/master/Software/ESPHome/6chan_energy_meter_main_board.yaml
          curl -L -o 6chan_energy_meter_main_ethernet.yaml https://raw.githubusercontent.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/master/Software/ESPHome/6chan_energy_meter_main_ethernet.yaml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install ESPHome
        run: | 
          pip3 install wheel
          pip3 install esphome

      - name: Get ESPHome version
        id: esphome_version
        run: |
          version=$(esphome version | grep 'Version:' | sed 's/Version: //')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Compile ESPHome
        run: esphome compile "${{ matrix.files }}"

      - name: Debug - Show build folder
        run: ls -R .esphome/build

      - name: Create a firmware directory
        run: mkdir -p firmware

      - name: Move the single combined file
        run: |
          device_name=$(basename "${{ matrix.files }}" .yaml)
          find .esphome/build -type f -name "firmware*.bin" -exec \
            mv {} "firmware/${device_name}-${{ steps.esphome_version.outputs.version }}.bin" \;

      - name: Debug - List firmware folder
        run: ls -R firmware || echo "firmware folder empty"
          
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true     # keep token for subsequent git push
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit firmware to repo
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add firmware
          git commit -m "Add compiled firmware for all devices" || echo "No changes to commit."
          git push
