name: Build ESPHome Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual runs

permissions:
  contents: write
  
jobs:
  build-firmware:
    runs-on: ubuntu-latest
    name: build
    strategy:
      matrix:
        files:
          - "circuitsetup-gdo-default.yaml"
          - "6chan_energy_meter_main_board.yaml"
          - "6chan_energy_meter_main_ethernet.yaml"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download ESPHome Config Files
        run: |
          curl -L -o circuitsetup-gdo-default.yaml https://raw.githubusercontent.com/CircuitSetup/circuitsetup-esphome/master/circuitsetup-gdo-default.yaml
          curl -L -o 6chan_energy_meter_main_board.yaml https://raw.githubusercontent.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/master/Software/ESPHome/6chan_energy_meter_main_board.yaml
          curl -L -o 6chan_energy_meter_main_ethernet.yaml https://raw.githubusercontent.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/master/Software/ESPHome/6chan_energy_meter_main_ethernet.yaml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install ESPHome
        run: | 
          pip3 install wheel
          pip3 install esphome

      - name: Get ESPHome version
        id: esphome_version
        run: |
          version=$(esphome version | grep 'Version:' | sed 's/Version: //')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Compile ESPHome
        run: esphome compile "${{ matrix.files }}"

      - name: Create a firmware directory
        run: mkdir -p firmware

      - name: Move the single combined file
        id: firmware
        run: |
          filename=$(basename "${{ matrix.files }}" .yaml)-${{ steps.esphome_version.outputs.version }}.bin
          find .esphome/build -type f -name "firmware*.bin" -exec \
            mv {} "firmware/${filename}" \;
          echo "filename=$filename" >> $GITHUB_OUTPUT

      - name: Build Manifest for secplus GDO
        if: github.event.release  
        run: |
          ruby ./scripts/update-espwebtools-manifests.rb
        env:
          MANIFEST_NAME: CircuitSetup Security+ Garage Door Opener
          MANIFEST_FNAME: manifest_secplus_gdo.json
          MANIFEST_VERSION: ""          
          ESP32_S3_IMAGE_URI: https://circuitsetup.github.io/ESPWebInstaller/${{ steps.firmware.outputs.filename }}
        
      - name: Commit firmware to repo
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add firmware
          git add manifests
          git commit -m "Add compiled firmware for all devices" || echo "No changes to commit."
          git push --force origin HEAD:main
          
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true     # keep token for subsequent git push
          token: ${{ secrets.GITHUB_TOKEN }}
