name: Build and Deploy Props Firmware

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Time Circuits Display"
            path: "CircuitSetup/Time-Circuits-Display"
            folder: "Software/"
          - name: "Flux Capacitor"
            path: "CircuitSetup/Flux-Capacitor"
            folder: ""
          - name: "SID"
            path: "CircuitSetup/SID"
            folder: ""
          - name: "Dash-Gauges"
            path: "CircuitSetup/Dash-Gauges"
            folder: ""
          - name: "Remote"
            path: "CircuitSetup/Remote"
            folder: ""

    steps:
      - name: Checkout Builder Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          pip install platformio
          pip install esptool

      - name: Clone Target Repo
        run: |
          git clone https://github.com/${{ matrix.path }} target_repo

      - name: Build Firmware with PlatformIO
        run: |
          pio run -d target_repo/${{ matrix.folder }}

      - name: Extract and Normalize Firmware Version
        id: get_version
        run: |
          RAW_VERSION=$(grep -hE '#define\s+[A-Z_]*VERSION\s+"[Vv][0-9.]+"' target_repo/${{ matrix.folder }}src/*_global.h | head -n 1 | sed -E 's/.*VERSION\s+"[Vv]([0-9.]+)".*/\1/')
          VERSION="v$RAW_VERSION"
          echo "Extracted normalized version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Rename Firmware Binary
        id: rename
        run: |
          BIN_PATH=$(find target_repo/${{ matrix.folder }}.pio/build/esp32dev -name firmware.bin | head -n 1)
          if [ -z "$BIN_PATH" ]; then
            echo "❌ Firmware binary not found!"
            exit 1
          fi
          # Replace spaces with underscores in matrix.name
          SAFE_NAME=$(echo "${{ matrix.name }}" | tr ' ' '_')
          NEW_NAME="${SAFE_NAME}_${{ steps.get_version.outputs.version }}.bin"
          mv "$BIN_PATH" "target_repo/$NEW_NAME"
          echo "✅ Renamed firmware binary to $NEW_NAME"
          echo "new_name=$NEW_NAME" >> "$GITHUB_OUTPUT"

      - name: Verify Binary Presence
        run: ls -la target_repo/.pio/build/esp32dev/

      - name: Create Release on Target Repo
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          repository: ${{ matrix.path }}
          tag_name: "${{ steps.get_version.outputs.version }}"
          name: "${{ matrix.name }} Firmware ${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            target_repo/${{ steps.rename.outputs.new_name }}
          fail_on_unmatched_files: true


